# Generated by Django 4.1.7 on 2023-02-22 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingOfExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experienced_age', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=2500)),
                ('moderator_validation', models.CharField(choices=[('NOP', 'Not processed yet'), ('VAL', 'Validated'), ('REJ', 'Rejected')], max_length=20)),
                ('likes', models.JSONField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SharingOfExperience_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
