# Generated by Django 4.1.7 on 2023-03-06 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_birth_date'),
        ('sharingofexperience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModelSharingOfExperiencesUserHasAccess',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sharing_of_experiences_user_has_access', models.JSONField()),
            ],
        ),
    ]
